# Update your service
apiVersion: v1
kind: Service
metadata:
  name: ets-user-service-svc
  namespace: ets-dev
spec:
  type: ClusterIP
  selector:
    app: ets-user-service
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
