apiVersion: v1
kind: ConfigMap
metadata:
  name: ets-user-service-config
  namespace: dev
data:
  DATABASE_URL: postgresql://postgres:root@host.docker.internal:5432/kubmicro?schema=user_service
  JWT_REFRESH_SECRET: your_super_secret_refresh_token_key_here
  JWT_SECRET: your_super_secret_access_token_key_here
  PORT: "4000"
  REDIS_URL: redis://host.docker.internal:6379
