apiVersion: v1
kind: Service
metadata:
  name: gym-app-service
  namespace: gym-dev
spec:
  type: ClusterIP
  selector:
    app: gym-app
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
